config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root to: 'lists#index'
  # Defines the root path route ("/")
  # root "posts#index"
  resources :bookmarks, only: [:destroy]
  resources :reviews, only: [:destroy]
  resources :lists, only: [:index, :show, :create, :destroy] do
    resources :bookmarks, only: [:create]
    resources :reviews, only: [:create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews, dependent: :destroy
  has_one_attached :photo

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :rating, presence: true
  validates :content, presence: true
  RANGE = (0..5)
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: RANGE }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(strong_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      # when it doesnt save -> show the form again
      render 'lists/show', status: :unprocessable_entity # throws a 422 (for Turbo)
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def strong_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
    @bookmark = Bookmark.new
    @review = Review.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(strong_params)
    if @list.save
      redirect_to lists_path
    else
      # when it doesnt save -> show the form again
      render 'index', status: :unprocessable_entity # throws a 422 (for Turbo)
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def strong_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @list = List.find(params[:list_id])
    @review = Review.new(strong_params)
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      render '../views/lists/show.html.erb', status: :unprocessable_entity # throws a 422 (for Turbo)
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to list_path(@review.list)
  end

  private

  def strong_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class="navbar navbar-expand-sm navbar-light fixed-top navbar-lewagon">
      <div class="container-fluid">
        <%= link_to lists_path, class:"navbar-brand" do %>
          <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" />
        <% end %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <li class="nav-item active">
              <%= link_to "My lists", lists_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact me</a>
            </li>
            <li class="nav-item dropdown">
              <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://avatars.githubusercontent.com/u/175819545?v=4" />
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" data-turbo-method="delete" href="#">Log out</a>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <%= yield %>
    <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
    </div>
  </body>
</html>

app/views/lists/_model_button.html.erb
<button type="button" class="btn" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo"><i class="fa-solid fa-plus"></i></i> <%= message %></button>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel"><%= message %></h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= simple_form_for model do |f| %>
        <div class="modal-body">
          <%= f.association :movie %>
          <%= f.input :comment %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= f.submit "submit", class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_url('banner.jpg') %>)">
  <div class="container">
    <h1>Your <strong>watch list</strong>!</h1>
    <p>What can I say? This is the best personal watch list!!</p>
  </div>
</div>
<div class="mt-3">
  <div class="cards">
    <% @lists.each do |list| %>
      <div class="list-card">
        <%= link_to list_path(list),class: "trash-icon", data: { turbo_method: :delete, turbo_confirm: "are you sure?" } do %>
          <i class="fa-solid fa-trash"></i>
        <% end %>
        <%= image_tag 'list-card.jpg' %>
        <%= link_to list_path(list), class: "text-decoration-none text-black" do %>
          <div class="list-card-info">
            <h2><%= list.name %></h2>
            <p>Hover over it!</p>
          </div>
        <% end %>
      </div>
    <% end %>
    <button type="button" class="btn p-0 border-0 bg-transparent text-success fs-1" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo"><i class="fa-solid fa-square-plus"></i></button>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Create a new list!</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <%= simple_form_for @list do |f| %>
            <div class="modal-body">
              <%= f.input :name %>
              <%# f.input :photo, as: :file %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <%= f.submit "submit", class: 'btn btn-success' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_url('banner-show.jpg') %>)">
  <div class="container">
    <h1><%= @list.name %></h1>
  </div>
</div>
<div class="justify-content-between m-3 d-flex">
  <h3><%= @bookmarks.count %> bookmarks found</h3>
  <%= render "lists/model_button", model: [@list, @bookmark], message: "Add a new movie" %>
</div>
<div class="cards">
  <% @bookmarks.each do |bookmark| %>
    <div class="card-pick">
      <%= image_tag bookmark.movie.poster_url, alt: "img" %>
      <div class="card-pick-info">
        <h2><%= bookmark.movie.title %></h2>
        <p><%= bookmark.movie.overview %></p>
        <p>
          <% bookmark.movie.rating.times do %>
            <i class="fa-solid fa-star"></i>
          <% end %>
        </p>
      </div>
      <%= link_to bookmark_path(bookmark),class: "trash-icon", data: { turbo_method: :delete, turbo_confirm: "are you sure?" } do %>
        <i class="fa-solid fa-trash"></i>
      <% end %>
    </div>
  <% end %>
</div>
<div class="reviews-block">
  <div class="container border-top">
    <div class="row mt-3">
      <div class="col-8 mt-3">
        <h3>Reviews</h3>
        <div class="reviews">
          <% if @list.reviews.any? %>
            <% @list.reviews.each do |review|%>
              <div class="row justify-content-between align-items-center">
                <div class="col-8 flex-grow-1">
                  <strong><%= review.content %></strong>
                </div>
                <div class="col-3 d-flex justify-content-end">
                  <% review.rating.times do %>
                    <i class="fa-solid fa-star"></i>
                  <% end %>
                </div>
                <div class="col-1">
                  <%= link_to review_path(review), data: { turbo_method: :delete, turbo_confirm: "are you sure?" } do %>
                    <i class="fa-solid fa-trash"></i>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="col-4 mt-3">
        <%= simple_form_for [@list, @review] do |f| %>
          <%= f.input :content %>
          <div class="star-rating">
            <%#= f.collection_radio_buttons :rating, [[1], [2], [3], [4], [5]], :first, :last do |b| %>
              <%#= b.radio_button%>
              <%# end %>
              <input type="radio" name="review[rating]" value="1" />
              <input type="radio" name="review[rating]" value="2" />
              <input type="radio" name="review[rating]" value="3" checked />
              <input type="radio" name="review[rating]" value="4" />
              <input type="radio" name="review[rating]" value="5" />
            </div>
            <%= f.submit :submit, class: "btn btn-secondary my-3"%>
          <% end %>
        </div>
      </div>
    </div>
  </div>